trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker build -t test-container .
  displayName: 'Build test'
  

- script: |
    apt install locales-all
    docker run test-container
  displayName: 'Run tests'

  # todo: another script here to produce a home brew tap 
