trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo localectl set-locale LANG=en_CA.UTF-8
    docker build -t test-container .
  displayName: 'Build test'
  

- script: |
    docker run test-container
  displayName: 'Run tests'

  # todo: another script here to produce a home brew tap 
